import { ClassItem, Enrollment } from "@/lib/types";

export const classes: ClassItem[] = [
  {
    id: "kids-swim-1",
    title: "Splash Starters",
    audience: "kids",
    category: "sports",
    instructor: "Nadia Rolle",
    location: "Nassau Aquatic Center",
    lat: 25.0443,
    lng: -77.3504,
    rating: 4.8,
    reviews: 124,
    price: 32,
    schedule: "Tue & Thu, 16:00",
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1622629797619-c100e3e67e2e?w=1200&q=80",
    shortDescription: "Foundational swim confidence for young learners.",
    longDescription:
      "A playful beginner swimming program focused on safety, confidence, and movement fundamentals with certified instructors.",
    tags: ["water safety", "beginner", "kids"],
  },
  {
    id: "kids-art-1",
    title: "Color Lab",
    audience: "kids",
    category: "arts",
    instructor: "Mia Johnson",
    location: "Downtown Arts House",
    lat: 25.069,
    lng: -77.3358,
    rating: 4.9,
    reviews: 89,
    price: 28,
    schedule: "Sat, 10:00",
    duration: "90 min",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200&q=80",
    shortDescription: "Creative expression through paint, texture, and color.",
    longDescription:
      "Kids explore painting and mixed media while developing confidence and fine motor skills in a supportive studio environment.",
    tags: ["creative", "art", "weekend"],
  },
  {
    id: "teens-code-1",
    title: "Build Your First App",
    audience: "teens",
    category: "tech",
    instructor: "Darian Smith",
    location: "Tech Hub Paradise Island",
    lat: 25.0832,
    lng: -77.3216,
    rating: 4.9,
    reviews: 203,
    price: 45,
    schedule: "Mon & Wed, 18:00",
    duration: "120 min",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80",
    shortDescription: "Hands-on React and product thinking for teens.",
    longDescription:
      "A practical coding studio where teens ideate, design, and ship simple app experiences while learning modern web fundamentals.",
    tags: ["coding", "react", "portfolio"],
  },
  {
    id: "teens-dance-1",
    title: "Street Motion",
    audience: "teens",
    category: "sports",
    instructor: "Kori Dean",
    location: "Pulse Studio Nassau",
    lat: 25.0484,
    lng: -77.3582,
    rating: 4.7,
    reviews: 142,
    price: 35,
    schedule: "Fri, 19:00",
    duration: "75 min",
    image: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=1200&q=80",
    shortDescription: "High-energy choreography and performance confidence.",
    longDescription:
      "A weekly dance lab for teens combining musicality, movement, and stage confidence in a strong group culture.",
    tags: ["dance", "performance", "energy"],
  },
  {
    id: "adults-yoga-1",
    title: "Coastal Flow Yoga",
    audience: "adults",
    category: "wellness",
    instructor: "Anya Clarke",
    location: "Cable Beach Wellness Loft",
    lat: 25.0804,
    lng: -77.4244,
    rating: 4.9,
    reviews: 173,
    price: 38,
    schedule: "Daily, 07:00",
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1200&q=80",
    shortDescription: "Mindful movement for strength and clarity.",
    longDescription:
      "An adult wellness class designed to improve mobility, strength, and calm through guided breathwork and flowing sequences.",
    tags: ["wellness", "mindfulness", "daily"],
  },
  {
    id: "adults-cooking-1",
    title: "Island Culinary Mastery",
    audience: "adults",
    category: "cooking",
    instructor: "Chef Lorenzo Bain",
    location: "Harbor Kitchen Studio",
    lat: 25.0586,
    lng: -77.3431,
    rating: 4.8,
    reviews: 117,
    price: 62,
    schedule: "Sun, 17:00",
    duration: "150 min",
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=1200&q=80",
    shortDescription: "Refined Caribbean techniques and plating.",
    longDescription:
      "A hands-on culinary workshop blending local ingredients, technique fundamentals, and elevated presentation.",
    tags: ["culinary", "skills", "weekend"],
  },
];

export const userEnrollments: Enrollment[] = [
  {
    id: "enr-1",
    classId: "kids-swim-1",
    studentName: "Lena Cooper",
    nextSession: "2026-03-26 16:00",
    status: "active",
  },
  {
    id: "enr-2",
    classId: "teens-code-1",
    studentName: "Kai Cooper",
    nextSession: "2026-03-25 18:00",
    status: "active",
  },
];
